[workspace]
name = "lion-guardians"
channels = [
    # Uncomment the following lines to use local channels for development.
    # "file:///tmp/ecoscope-workflows/release/artifacts/",
    "file:///tmp/ecoscope-workflows-custom/release/artifacts/",
    'https://repo.prefix.dev/ecoscope-workflows/',
    'https://repo.prefix.dev/ecoscope-workflows-custom/',
    'conda-forge',
]
platforms = ['linux-64', 'osx-arm64','win-64']

[dependencies]
curl = "*"
rattler-build = "*"
yq = "*"
hatch = "*"
pip="*"
hatch-vcs="*"

[feature.compile.dependencies]
# Include this if you add new tasks and the package has been built
ecoscope-workflows-ext-lion-guardians = "*"

ecoscope-workflows-ext-ste = "0.0.6.*"
ecoscope-workflows-ext-mnc = "0.0.0.*"
ecoscope-workflows-core = "0.20.4.*"
ecoscope-workflows-ext-custom = "0.0.20.*"
# Here we don't specify the channel on purpose, as we want to use the local channel if it exists,
# otherwise we fall back to the remote channel.
# If you want to ensure a specific channel to incorporate your local changes, you can uncomment the line below.
# ecoscope-workflows-core = { version = "*", channel = "file:///tmp/ecoscope-workflows/release/artifacts/" }
# ecoscope-workflows-ext-lion-guardians = { version = "*", channel = "file:///tmp/ecoscope-workflows-custom/release/artifacts/" }

[environments]
compile = { features = [
    "compile",
], solve-group = "compile", no-default-feature = true }

[tasks]
[tasks.build-release]
cmd = './publish/build.sh'

[tasks.pytest-310]
cmd = './dev/pytest-task.sh 310'

[tasks.pytest-311]
cmd = './dev/pytest-task.sh 311'

[tasks.pytest-312]
cmd = './dev/pytest-task.sh 312'

[feature.compile.tasks.compile-collared_lions]
cmd = './dev/recompile.sh collared_lions --install'
depends-on = ["build-release"]

[feature.compile.tasks.recompile-collared_lions]
cmd = './dev/recompile.sh collared_lions --update'
depends-on = ["build-release"]

[feature.compile.tasks.compile-guardians_report]
cmd = './dev/recompile.sh guardians_report --install'
depends-on = ["build-release"]

[feature.compile.tasks.recompile-guardians_report]
cmd = './dev/recompile.sh guardians_report --update'
depends-on = ["build-release"]
